// Generated by ts-to-zod
import { z } from "zod";

export const permissionLevelSchema = z
	.union([z.literal("reader"), z.literal("writer"), z.literal("admin")])
	.nullable();

export const userPermissionsDTOSchema = z.object({
	UID: z.string().min(1),
	Equipment: permissionLevelSchema.optional(),
});
